language: rust
rust:
  - nightly

script:
  - make all
  - make travistest
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then make bench ; fi

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    -
    - RELEASE=true
